pipeline {
    agent any

    environment {
        IMAGE_NAME = 'static-site-demo'
        DOCKERHUB_USER = 'your_dockerhub_username'  // replace this
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/<your-username>/dockerized-app-jenkins-pipeline.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('my-app') {
                        sh 'docker build -t $DOCKERHUB_USER/$IMAGE_NAME:latest .'
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $DOCKER_USER/$IMAGE_NAME:latest'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker stop static-site || true && docker rm static-site || true'
                sh 'docker run -d --name static-site -p 8080:80 $DOCKERHUB_USER/$IMAGE_NAME:latest'
            }
        }
    }
}
